// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLd6c3rftApYv7J8fQodMdc1dQNwoIG4o',
    appId: '1:310814421512:web:bd56a16bb0b67216b257bd',
    messagingSenderId: '310814421512',
    projectId: 'e-stock0',
    authDomain: 'e-stock0.firebaseapp.com',
    storageBucket: 'e-stock0.appspot.com',
    measurementId: 'G-BW69DTSN3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcW-tAK2NfMD19q82oCj_bQ6MqT5uODY8',
    appId: '1:310814421512:android:6000922201915aceb257bd',
    messagingSenderId: '310814421512',
    projectId: 'e-stock0',
    storageBucket: 'e-stock0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgIC68lLwB6OpdVQa8YuN6r_NMLlk7now',
    appId: '1:310814421512:ios:eb08382b28e8a45eb257bd',
    messagingSenderId: '310814421512',
    projectId: 'e-stock0',
    storageBucket: 'e-stock0.appspot.com',
    iosClientId: '310814421512-ti2t3rb8ihbja0hrspk8g0tb55ur4lpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgIC68lLwB6OpdVQa8YuN6r_NMLlk7now',
    appId: '1:310814421512:ios:eb08382b28e8a45eb257bd',
    messagingSenderId: '310814421512',
    projectId: 'e-stock0',
    storageBucket: 'e-stock0.appspot.com',
    iosClientId: '310814421512-ti2t3rb8ihbja0hrspk8g0tb55ur4lpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eStock',
  );
}
